ur_real_album/config/routes.rb
UrRealAlbum::Application.routes.draw do

  resources :albums
  resources :rules

  root to: 'home#index'

end

ur_real_album/app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :title, :description
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true

  has_many :stickers
  has_many :rules
  has_many :chosen_albums
  has_many :users, through: :chosen_albums
end

ur_real_album/app/models/chosen_album.rb
class ChosenAlbum < ActiveRecord::Base
  attr_accessible :state, :user, :album
  validates :state, presence: true

  belongs_to :user
  belongs_to :album
end

ur_real_album/app/models/rule.rb
class Rule < ActiveRecord::Base
  attr_accessible :name, :description
  validates :name, presence: true
  validates :description, presence: true

  belongs_to :album
  belongs_to :user
end

ur_real_album/app/models/sticker.rb
class Sticker < ActiveRecord::Base
  attr_accessible :name, :image
  validates :name, presence: true

  belongs_to :album
end

ur_real_album/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true

  has_many :rules
  has_many :chosen_albums
  has_many :albums, through: :chosen_albums
end

ur_real_album/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def new
  	@album = Album.new
  end

  def create
    @album = Album.new(params[:album])

    if @album.save
    	redirect_to @album
    else
    	render 'new'
    end
  end

  def show
    @album = Album.find(params[:id])
   end
end

ur_real_album/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

ur_real_album/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @albums = Album.all
  end
end

ur_real_album/app/controllers/rules_controller.rb
class RulesController < ApplicationController

  def new
    @rule = Rule.new
  end

  def create
    @rule = Rule.new(params[:rule])
    if @rule.save
      redirect_to @rule
    else
      render 'new'
    end
  end

  def show
    @rule = Rule.find(params[:id])
  end

end

ur_real_album/app/controllers/session_controller.rb
class SessionController
  attr_accessor :users

  def initialize
    @users = Array.new
  end

  def add_user(user)
    @users << user
  end

  def is_valid?(email, password)
    user = users.detect{|a| a.email == email}
    !user.nil? ? (user.password == password ? true : false) : false
  end
end

ur_real_album/app/controllers/user_controller.rb
class UserController < ApplicationController
end

ur_real_album/app/helpers/albums_helper.rb
module AlbumsHelper
end

ur_real_album/app/helpers/application_helper.rb
module ApplicationHelper
end

ur_real_album/app/helpers/home_helper.rb
module HomeHelper
end

ur_real_album/app/helpers/rules_helper.rb
module RulesHelper
end

ur_real_album/app/helpers/user_helper.rb
module UserHelper
  def add_album(album, user)
    unless user.albums.include?(album)
      chosen_album = ChosenAlbum.new(user: user, album: album, state: "selected")
      album.chosen_albums << chosen_album
      user.chosen_albums << chosen_album
      chosen_album.save!
      user.save!
      album.save!
    else 
      raise "This album has been already selected"
    end  
  end
end

ur_real_album/app/views/albums/index.html.erb
<h1>Listing posts</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @albums.each do |album| %>
    <tr>
      <td><%= link_to album.title , album %></td>
      <td><%= album.description %></td>
    </tr>
  <% end %>
</table>

ur_real_album/app/views/albums/new.html.erb
<%= form_for :album, url: albums_path do |f| %>
  <% if @album.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@album.errors.count, "error") %> prohibited
      this album from being saved:</h2>
    <ul>
    <% @album.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', albums_path %>

ur_real_album/app/views/albums/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @album.description %>
</p>

ur_real_album/app/views/home/index.html.erb
<h1>Your real album</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
 
  <% @albums.each do |album| %>
    <tr>
      <td><%= link_to album.title , album %></td>
      <td><%= album.description %></td>
    </tr>
  <% end %>
</table>

ur_real_album/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrRealAlbum</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ur_real_album/app/views/rules/new.html.erb
<%= form_for :rule, url: rules_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

ur_real_album/app/views/rules/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @rule.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @rule.description %>
</p>